/**
 * Hook 7 Part A: CME Tracker routes
 *
 * GET /doctor/cme/summary?year=2026
 *   → Returns CME credits for the year, total hours, NMC progress.
 *
 * GET /doctor/cme/history?years=5
 *   → Returns per-year hour totals (for bar chart).
 *
 * GET /doctor/cme/certificate?year=2026
 *   → Returns a print-ready HTML certificate in NMC-acceptable format.
 */

import type { FastifyInstance } from "fastify";
import { requireDoctorAccess } from "../middleware/doctor-scope";
import { getCmeSummary, getCmeHistory } from "../services/cme-accrual.service";
import { prisma } from "../../db/client";

function renderNmcCertificateHtml(params: {
  doctorName: string;
  registrationNumber: string;
  year: number;
  totalHours: number;
  byEventType: Record<string, { count: number; hours: number }>;
  activities: Array<{ eventType: string; hours: number; awardedAt: Date }>;
  hospitalName: string;
}): string {
  const generatedAt = new Date().toLocaleDateString("en-IN", {
    day: "2-digit", month: "long", year: "numeric",
  });
  const EVENT_LABELS: Record<string, string> = {
    mdt_participation: "Multidisciplinary Team Meeting",
    case_documentation: "Clinical Case Documentation",
    referral_accepted: "Referral Case Review",
    defense_mode_export: "Medical Record Documentation",
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>CME Certificate — ${params.doctorName} — ${params.year}</title>
  <style>
    body { font-family: 'Times New Roman', serif; max-width: 760px; margin: 40px auto; color: #1a1a1a; }
    .border-box { border: 3px double #1a3c6b; padding: 40px; }
    .header { text-align: center; margin-bottom: 24px; }
    .header h1 { font-size: 22pt; color: #1a3c6b; margin: 0; }
    .header h2 { font-size: 14pt; color: #1a3c6b; margin: 4px 0; }
    .header p { color: #444; margin: 4px 0; }
    .cert-body { margin: 24px 0; font-size: 12pt; line-height: 1.8; }
    .cert-body .name { font-size: 16pt; font-weight: bold; color: #1a3c6b; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 11pt; }
    th { background: #1a3c6b; color: white; padding: 6px 10px; text-align: left; }
    td { border: 1px solid #ccc; padding: 6px 10px; }
    tr:nth-child(even) td { background: #f5f7fb; }
    .total-row td { font-weight: bold; background: #e8eef6; }
    .footer { margin-top: 32px; text-align: center; font-size: 10pt; color: #666; border-top: 1px solid #ccc; padding-top: 12px; }
    .hash-note { font-size: 8pt; color: #999; margin-top: 8px; font-family: monospace; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
<div class="border-box">
  <div class="header">
    <h1>CONTINUING MEDICAL EDUCATION</h1>
    <h2>CERTIFICATE OF COMPLETION</h2>
    <p>Issued under the National Medical Commission CPD Framework</p>
    <p>Care Setu Clinical Platform · ${params.hospitalName}</p>
  </div>

  <div class="cert-body">
    <p>This is to certify that</p>
    <p class="name">Dr. ${params.doctorName}</p>
    <p>
      Registration No.: <strong>${params.registrationNumber || "—"}</strong> &nbsp;|&nbsp;
      Hospital: <strong>${params.hospitalName}</strong>
    </p>
    <p>
      has completed the following Continuing Professional Development activities
      through the Care Setu oncology care platform during the period
      <strong>1 January ${params.year} to 31 December ${params.year}</strong>,
      accruing a total of <strong>${params.totalHours} CME hours</strong>.
    </p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Activity Type</th>
        <th>Sessions</th>
        <th>CME Hours</th>
      </tr>
    </thead>
    <tbody>
      ${Object.entries(params.byEventType).map(([type, { count, hours }]) => `
        <tr>
          <td>${EVENT_LABELS[type] ?? type}</td>
          <td>${count}</td>
          <td>${hours.toFixed(2)}</td>
        </tr>`).join("")}
      <tr class="total-row">
        <td>TOTAL</td>
        <td>${Object.values(params.byEventType).reduce((s, v) => s + v.count, 0)}</td>
        <td>${params.totalHours}</td>
      </tr>
    </tbody>
  </table>

  <p style="font-size:10pt; color:#666; margin-top:16px;">
    This certificate is generated electronically and is tamper-evident.
    Activities are verified through the Care Setu platform's audit trail.
    Issued on: <strong>${generatedAt}</strong>.
  </p>

  <div class="footer">
    <p>Care Setu — Oncology Care Platform &nbsp;|&nbsp; caresetu.in</p>
    <p class="hash-note">Verification: certificate generated by Care Setu platform. Activities logged in AuditLog.</p>
  </div>
</div>
</body>
</html>`;
}

export function registerDoctorCmeRoutes(fastify: FastifyInstance) {
  const auth = [(fastify as any).authenticate, requireDoctorAccess];

  // ─── CME summary ─────────────────────────────────────────────────────────

  fastify.get("/doctor/cme/summary", { preHandler: auth }, async (request) => {
    const user = (request as any).user as { doctorId: string };
    const query = request.query as { year?: string };
    const year = query.year ? parseInt(query.year, 10) : undefined;
    return await getCmeSummary(user.doctorId, year);
  });

  // ─── CME history (multi-year) ─────────────────────────────────────────────

  fastify.get("/doctor/cme/history", { preHandler: auth }, async (request) => {
    const user = (request as any).user as { doctorId: string };
    const query = request.query as { years?: string };
    const years = Math.min(Number(query.years ?? 5), 10);
    return await getCmeHistory(user.doctorId, years);
  });

  // ─── NMC certificate ──────────────────────────────────────────────────────

  fastify.get("/doctor/cme/certificate", { preHandler: auth }, async (request, reply) => {
    const user = (request as any).user as { doctorId: string };
    const query = request.query as { year?: string };
    const year = query.year ? parseInt(query.year, 10) : new Date().getFullYear();

    const [summary, doctor] = await Promise.all([
      getCmeSummary(user.doctorId, year),
      prisma.doctor.findUnique({
        where: { id: user.doctorId },
        select: { name: true, hospitalName: true, registrationNumber: true },
      }),
    ]);

    const html = renderNmcCertificateHtml({
      doctorName: doctor?.name ?? "Doctor",
      registrationNumber: doctor?.registrationNumber ?? "",
      year,
      totalHours: summary.totalHours,
      byEventType: summary.byEventType,
      activities: summary.credits.map((c) => ({
        eventType: c.eventType,
        hours: c.hours,
        awardedAt: new Date(c.awardedAt),
      })),
      hospitalName: doctor?.hospitalName ?? "",
    });

    return reply
      .header("Content-Type", "text/html; charset=utf-8")
      .send(html);
  });
}
